version: '3'
services:
  bleu-daemon:
    container_name: bleu-daemon
    build: ./bleu-daemon
    ports:
      - "9999:9999"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db
    volumes:
      - ./bleu-daemon/task:/bleu-daemon/task
      - ./bleu-daemon/schema:/bleu-daemon/schema
      - ./bleu-daemon/config.docker.toml:/bleu-daemon/config.toml
  bleu-server:
    container_name: bleu-server
    build: ./bleu-server
    ports:
      - "8888:8888"
    depends_on:
      - db
    environment:
      - POSTGRES_URL=postgres://root:postgresql@db:5432/postgres
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8888
  db:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=postgresql
    ports:
      - "5432:5432"
