version: '3'

services:
  bleu-daemon:
    image: onthertech/optimism.explorer.daemon:latest
    build:
      context: ./bleu-daemon
      dockerfile: Dockerfile
    ports:
      - 9999:9999
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - db
    volumes:
      - ./bleu-daemon/task:/bleu-daemon/task
      - ./bleu-daemon/schema:/bleu-daemon/schema
      - ./bleu-daemon/config.docker.toml:/bleu-daemon/config.toml
  bleu-server:
    image: onthertech/optimism.explorer.server:latest
    build:
      context: ./bleu-server
      dockerfile: Dockerfile
    env_file:
      - ./bleu-server/.env.docker
    ports:
      - 8888:8888
    depends_on:
      - db
  bleu-app:
    image: onthertech/optimism.explorer.app:latest
    build:
      context: ./bleu-app
      dockerfile: Dockerfile
      args:
        NODE_ENV: goerli
    ports:
      - 3000:3000
  db:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=postgresql
    ports:
      - 5432:5432
